# This workflow will do a clean install of node dependencies, build the source code
# and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Extract CMS Data

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: "14"
              env:
                  PRISMIC_API_ENDPOINT: ${{ secrtes.PRISMIC_API_ENDPOINT }}
                  PRISMIC_ACCESS_TOKEN: ${{ secrtes.PRISMIC_ACCESS_TOKEN }}
            - run: npm install
            - run: node src/scripts/extract-data.js
            - run: git add content/
            - run: git commit content/ -m 'Updated content from CMS'
            - run: git push origin master
